### ISSUE TITLE
Hanging on forever

### ISSUE THREAD

**Issue by janmg** [4tronix/Robobit#2]
I have a Robobit Mk3 and two microbit V2's and the simplest programs hang if I upload them through MakeCode. If I read from the sensor I get one reading and then the microbit hangs with a 0x20 with a frowny face, so with a reset I get a new reading. Somehow it runs out of memory.

**Comment by 4tronix** [comment]
HI,
Yes, this is a problem with Makecode and the Makecode team have already 
fixed it.
However they haven't yet released the fix into the release version, so 
you have to use the Beta release here: 
https://makecode.microbit.org/beta

Best regards,
Gareth

------ Original Message ------

**Comment by janmg** [comment]
Yes! ... Beta release works much better. Now the robot is nicely bouncing around and the kids will have some programming to do =)
